spring.application.name=hm
server.port=8081

spring.datasource.url=jdbc:mysql://ejercicio4-practica2.j.aivencloud.com:15402/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_b0s9xlq6Bb54hIffJqg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect